// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLDsXe4WVjaLx02cQD4GwLNic0JU7kMrg',
    appId: '1:80911372143:web:e728d80514817b8d52e29a',
    messagingSenderId: '80911372143',
    projectId: 'cadayfinalapplicationproject',
    authDomain: 'cadayfinalapplicationproject.firebaseapp.com',
    storageBucket: 'cadayfinalapplicationproject.firebasestorage.app',
    measurementId: 'G-MQPW5XVPT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusgNC3ucf5nW72vZcK3gkhRe00w8oj9Y',
    appId: '1:80911372143:android:5357fa421e2b8a0952e29a',
    messagingSenderId: '80911372143',
    projectId: 'cadayfinalapplicationproject',
    storageBucket: 'cadayfinalapplicationproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeOhFWkh6SaEafigr2u9mKlDOiwD-Nb8A',
    appId: '1:80911372143:ios:e452e195d797bc2452e29a',
    messagingSenderId: '80911372143',
    projectId: 'cadayfinalapplicationproject',
    storageBucket: 'cadayfinalapplicationproject.firebasestorage.app',
    iosBundleId: 'com.example.cadayFinalApplications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeOhFWkh6SaEafigr2u9mKlDOiwD-Nb8A',
    appId: '1:80911372143:ios:e452e195d797bc2452e29a',
    messagingSenderId: '80911372143',
    projectId: 'cadayfinalapplicationproject',
    storageBucket: 'cadayfinalapplicationproject.firebasestorage.app',
    iosBundleId: 'com.example.cadayFinalApplications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLDsXe4WVjaLx02cQD4GwLNic0JU7kMrg',
    appId: '1:80911372143:web:586629b70943bc4f52e29a',
    messagingSenderId: '80911372143',
    projectId: 'cadayfinalapplicationproject',
    authDomain: 'cadayfinalapplicationproject.firebaseapp.com',
    storageBucket: 'cadayfinalapplicationproject.firebasestorage.app',
    measurementId: 'G-BDZ2XDHYCS',
  );
}
